USE [master]
GO
/****** Object:  Database [ProductsDb]    Script Date: 10/14/2025 8:36:18 AM ******/
CREATE DATABASE [ProductsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProductsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ProductsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ProductsDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProductsDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProductsDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProductsDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProductsDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProductsDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProductsDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProductsDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProductsDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProductsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProductsDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProductsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProductsDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProductsDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProductsDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProductsDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProductsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProductsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProductsDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProductsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProductsDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProductsDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ProductsDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProductsDb] SET RECOVERY FULL 
GO
ALTER DATABASE [ProductsDb] SET  MULTI_USER 
GO
ALTER DATABASE [ProductsDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProductsDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProductsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProductsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProductsDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProductsDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProductsDb', N'ON'
GO
ALTER DATABASE [ProductsDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [ProductsDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ProductsDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10/14/2025 8:36:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 10/14/2025 8:36:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](1000) NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Stock] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ProductsDb] SET  READ_WRITE 
GO
